---
- name: install postgres 14 and set up replication
  hosts: node1,node2
  become: yes
  pre_tasks:
  - name: Rename hostanme
    ansible.builtin.hostname:
      name: '{{ inventory_hostname }}'
      use: systemd
  
  roles:
   - install_postgres
   - postgres_replication

